title: Magical Girls Standards
description: Description goes here!
collections:
  standards:
    output: true
    permalink: /:title/
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: ""
      type: standards
    values:
      is_standard: true
      layout: "standard"
