title: Magical Girl Standards
description: Internet etiquette, magic and related tomfoolery
google_analytics: UA-110259127-1
collections:
  standards:
    output: true
    permalink: /:title/
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: ""
      type: standards
    values:
      is_standard: true
      layout: "standard"
plugins:
  - "jekyll-sitemap"
